[core]
	engine = pg
	plan_file = sqitch/sqitch.plan
	top_dir = sqitch
[user]
	name = Derek Gorthy
	email = derek@sidequestgroup.com
[engine "pg"]
	target = db:pg:pyrrho_data_dev
	registry = sqitch
[target "pyrrho_data_dev"]
	uri = db:pg:pyrrho_data_dev
[target "pyrrho_data_prod"]
	uri = db:pg:pyrrho_data_prod
