"""Email delivery — wraps api.email.send_email (Resend) with a brief layout."""
from __future__ import annotations

import logging
import os
from datetime import date

# Reuses the form4 email infra (Resend)
from api.email import send_email

log = logging.getLogger(__name__)

RECIPIENT = os.getenv("THESIS_MONITOR_TO", "derek.gorthy@gmail.com")


def render_html(*, brief_text: str, raw_block: str, hits_html: str = "") -> str:
    """Brief on top (LLM summary), raw data block at bottom for transparency."""
    brief_html = brief_text.replace("\n\n", "</p><p>").replace("\n", "<br>")
    return f"""
<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:680px;margin:0 auto;padding:24px;background:#0A0A0F;color:#E8E8ED;">
  <div style="margin-bottom:16px;">
    <span style="font-size:18px;font-weight:bold;color:#E8E8ED;">Thesis Monitor</span>
    <span style="margin-left:8px;font-size:13px;color:#8888A0;">{date.today().isoformat()}</span>
  </div>
  {hits_html}
  <div style="background:#12121A;border:1px solid #2A2A3A;border-radius:8px;padding:20px;margin-bottom:16px;">
    <h2 style="margin:0 0 12px;font-size:14px;color:#E8E8ED;letter-spacing:0.5px;text-transform:uppercase;">Daily Brief</h2>
    <div style="font-size:14px;color:#D4D4DC;line-height:1.55;"><p>{brief_html}</p></div>
  </div>
  <details style="background:#12121A;border:1px solid #2A2A3A;border-radius:8px;padding:12px 16px;">
    <summary style="cursor:pointer;font-size:12px;color:#8888A0;letter-spacing:0.5px;text-transform:uppercase;">Raw Data</summary>
    <pre style="font-size:11px;color:#A0A0B0;line-height:1.4;white-space:pre-wrap;margin-top:10px;">{raw_block}</pre>
  </details>
  <p style="margin-top:18px;font-size:11px;color:#55556A;">Generated by thesis_monitor on Mac Studio. Source: yfinance + FRED + Finnhub + NewsAPI + GLM-4.7-flash via Ollama.</p>
</div>
"""


def render_stop_banner(hits) -> str:
    if not hits:
        return ""
    rows = "".join(
        f'<li style="margin-bottom:6px;"><b>{h.label}</b> — {h.detail}. <i>{h.action}.</i></li>'
        for h in hits
    )
    return f"""
<div style="background:#3A0E1A;border:2px solid #C8102E;border-radius:8px;padding:14px 18px;margin-bottom:16px;">
  <div style="font-size:13px;color:#FF6B7A;letter-spacing:0.5px;text-transform:uppercase;font-weight:bold;margin-bottom:6px;">⚠ Stop(s) Tripped</div>
  <ul style="margin:0;padding-left:18px;color:#FFD0D8;font-size:13px;">{rows}</ul>
</div>
"""


def send_brief(brief_text: str, raw_block: str, hits=None) -> bool:
    subject_prefix = "⚠ " if hits else ""
    subject = f"{subject_prefix}Thesis Monitor — {date.today().isoformat()}"
    hits_html = render_stop_banner(hits or [])
    html = render_html(brief_text=brief_text, raw_block=raw_block, hits_html=hits_html)
    ok = send_email(to=RECIPIENT, subject=subject, html=html)
    if ok:
        log.info("Sent thesis monitor brief to %s", RECIPIENT)
    else:
        log.error("Failed to send thesis monitor brief")
    return ok
