#!/usr/bin/env python3
"""Freeze the given-name/surname discriminator used by name_cleaner.

name_cleaner has to answer one question to place a compound surname
correctly: for "SIMMONS SMITH CATHERINE", is "Catherine" a given name and
"Smith" a surname? Answering it needs population frequencies, but
clean_person_name() runs per-filing during ingest and must stay a pure
function with no DB round-trip. So the frequencies are learned once here and
committed as a static lexicon.

The training set is our own data, not an external name list: two-token EDGAR
names are unambiguous ground truth — position 0 is always the surname,
position 1 always the given name. ~42.7k of them yield a clean separation:

    denise  given 36  surname  0   ratio 37.0
    smith   given  0  surname 81   ratio  0.01

Only tokens that clear both a ratio and an evidence floor are emitted, so the
lexicon holds confident cases and stays silent on the rest — an unlisted
token means "no opinion", and the cleaner falls back to its default rotation.

Re-run when the insider table has grown enough to sharpen the counts. The
output is deterministic (sorted), so a no-op re-run produces no diff.

Usage (on Studio, which has the form4 DB):
    python3 scripts/build_name_lexicon.py
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from config.database import get_connection  # noqa: E402

OUT = Path(__file__).resolve().parents[1] / "strategies" / "insider_catalog" / "name_lexicon.json"

# A token is only admitted when it is lopsided AND backed by real counts.
# These mirror the constants in name_cleaner so the two cannot drift.
GIVEN_RATIO_MIN = 3.0
SURNAME_RATIO_MAX = 0.5
MIN_EVIDENCE = 3

SUFFIXES = {"jr", "sr", "ii", "iii", "iv", "v", "md", "phd", "cpa", "esq", "do", "dds"}


def norm(tok: str) -> str:
    return tok.lower().strip(".,'\"")


def is_initial(tok: str) -> bool:
    return len(re.sub(r"[^A-Za-z]", "", tok)) <= 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()

    conn = get_connection()
    rows = conn.execute(
        """SELECT name FROM insiders
            WHERE COALESCE(is_entity, 0) = 0 AND name IS NOT NULL AND name <> ''"""
    ).fetchall()
    conn.close()

    given, surname = Counter(), Counter()
    for r in rows:
        t = r["name"].split()
        if len(t) == 2 and not is_initial(t[1]) and norm(t[1]) not in SUFFIXES:
            surname[norm(t[0])] += 1
            given[norm(t[1])] += 1
    trained = sum(given.values())

    def ratio(tok: str) -> float:
        return (given[tok] + 1) / (surname[tok] + 1)

    givens = sorted(t for t in given if given[t] >= MIN_EVIDENCE and ratio(t) >= GIVEN_RATIO_MIN)
    surnames = sorted(t for t in surname if surname[t] >= MIN_EVIDENCE and ratio(t) <= SURNAME_RATIO_MAX)

    payload = {
        "_comment": "Generated by scripts/build_name_lexicon.py — do not hand-edit.",
        "trained_on_2token_names": trained,
        "given_ratio_min": GIVEN_RATIO_MIN,
        "surname_ratio_max": SURNAME_RATIO_MAX,
        "min_evidence": MIN_EVIDENCE,
        "given": givens,
        "surname": surnames,
    }
    args.out.write_text(json.dumps(payload, indent=1, sort_keys=False) + "\n")
    print(f"  trained on {trained} unambiguous 2-token names")
    print(f"  given tokens  : {len(givens)}")
    print(f"  surname tokens: {len(surnames)}")
    print(f"  wrote {args.out} ({args.out.stat().st_size / 1024:.0f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
